### ISSUE TITLE
Just wanted to say thank you for your repositories and all the hard work you put into it :heart: 

### ISSUE THREAD

**Issue by akaAbdullahMateen** [jishanshaikh4/start-here#7]
I am new to GitHub, and I do not know how to message someone (*I do not use social sites like LinkedIn* so I could not contact you on there*). Therefore, sorry for creating an issue to message you.

**Comment by jishanshaikh4** [comment]
> I am new to GitHub, and I do not know how to message someone (_I do not use social sites like LinkedIn_ so I could not contact you on there*). Therefore, sorry for creating an issue to message you.

Unfortunately, there is not messaging service here at GitHub, and I don't mind you creating an issue for this. 

Thank you for the kind words. I really appreciate that. Also, you can connect to me socially via Instagram, Facebook, or Twitter whichever way you prefer. My email is jishanshaikh9893@gmail.com for an immediate response about any project, idea, or discussion. 

Or, feel free to comment in this thread publicly :grin:

**Comment by akaAbdullahMateen** [comment]
I will contact you on your email for any discussion in future. Right now, I am studying web development from [MDN](https://developer.mozilla.org/en-US/docs/Learn/), and it's almost done - check out my repositories to get an idea of what I have learnt so far :smile: .

After completing this basic introduction to web development, I planned to study web frameworks (React + Redux + Ruby / Rails). I already know the basic data structures and algorithm, and I am decent with mathematics. But, I do not have a university degree. I was pursuing Mechatronics and Control Engineering from University of Engineering and Technology, Lahore, Pakistan - but due to financial and other reasons, I have to drop out in 6th semester.

Considering my situation and my interests align, what advice would you give to me for my career ahead? I am willing to study as much as I can from free resources online.

Initially, I thought about apply for remote jobs that do **not** require a degree. (*Have you or someone you know have any experience working these type of jobs? What would you advice?*) 

My second thought was to spend a little extra time studying everything that [this great roadmap](https://roadmap.sh/frontend) and [this one](https://roadmap.sh/backend) requires me to do. And then, apply to some decent full time jobs at fully remote companies. (*Hopefully they will hire me. What are your thoughts?*)

Other than that, I wish you all the best for your career ahead, and have a nice day :heart:
